{
 "title": "Project dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Subtask created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Subtasks_created_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Account",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Discard_task_total", "legendFormat": "__auto" },
    { "expr": "Get_task_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Storage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Failure_and_shortage_total", "legendFormat": "__auto" },
    { "expr": "Subtasks_requested_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Storage rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Warehouse_success_rate", "legendFormat": "__auto" }
   ]
  }
 ]
}