eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

server:
  port: 8084

spring:
  application:
    name: account-service

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./databases/accounts;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    generate-ddl: true


  output:
    ansi:
      enabled=ALWAYS: